config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
    
    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
      get :ranking
    end

    
    member do
      # 瀏覽個別餐廳的 Dashboard
      get :dashboard
      
      # 收藏 / 取消收藏
      post :favorite
      post :unfavorite

      # 喜歡 / 不喜歡
      post :like
      post :unlike

    end
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end

  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  resources :categories, only: :show
  root "restaurants#index"

  

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # 如果 User 已經有了評論，就不允許刪除帳號（刪除時拋出 Error）
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  # 「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  # 「使用者喜歡很多餐廳」的多對多關聯
  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  # 「使用者可以追蹤很多人」的多對多關聯
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  # 設定follower
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  # 設定friend關係
  has_many :friendships, dependent: :destroy
  has_many :friendings, through: :friendships

  # 設定inverse_friend關係(被加入朋友)
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friending_id"
  has_many :frienders, through: :inverse_friendships, source: :user

  mount_uploader :avatar, AvatarUploader

  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end
  
  def friending?(user)
    self.friendings.include?(user)
  end

  def all_friends 
    friends = self.friendings + self.frienders
    return friends.uniq
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :friend_list]

  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings.order(created_at: :desc)
    @followers = @user.followers.order(created_at: :desc)
  end

  def edit
    unless @user == current_user
      flash[:alert] = "非本人，無法編輯!"
      redirect_to root_path
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "profile was successfully updated"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "profile was failed to update"
      render :edit
    end
  end

  def friend_list
    @friends = current_user.all_friends
  end


  private

  def set_user
      @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3>Edit Profile</h3>
        <%= form_for [@user] do |f| %>  
          <div class="form-gruop">
            <%= f.label :name, "Name" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="form-gruop">
            <%= f.label :infor, "自我介紹" %>
            <%= f.text_area :intro,class: "form-control" %>
          </div>

          <div class="form-gruop">
            <%= f.label :avatar, "大頭照上傳" %>
            <%= image_tag @user.avatar if @user.avatar? %>
            <%= f.file_field :avatar %>
          </div>

          <div class="form-gruop">
            <%= f.submit "Update", class: "btn btn-primary" %>
            <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
          </div>  
        <% end %>
    </div>
  </div>
</div>

app/views/users/friend_list.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1>my friend</h1>
      <!-- 顯示加入朋友的人的清單 -->
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><strong><%= current_user.all_friends.count %></strong> friends</h3>
        </div>
        
        <ul class="list-group">
          <% @friends.each do |friend| %>
          <li class="list-group-item">
            <%= link_to user_path(friend) do %>
            <%= image_tag friend.avatar, height: 30, width: 30, class: "img-circle" %>
            
            <% if friend.name? %>
            <%= friend.name %>
            <% else %>
            <%= friend.email.split('@').first %>
            <% end %>
            
            <% end %>
          </li>
          <% end %>
        </ul>
        
      </div>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <!-- 使用 Bootstrap components 的 Nav Tabs -->
    <!-- https://getbootstrap.com/docs/3.3/components/#nav-tabs -->
    <ul class="nav nav-tabs">
      <li role="presentation">
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation" >
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
      <li role="presentation" class="active">
        <%= link_to '美食達人', users_path %>
      </li>
      <li role="presentation">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
     </li>
    </ul>

  </div>
</div>

<br>
<div class="container">
  <div class="row">

    <div class="col-md-10 col-md-offset-1">
      <h1>美食達人</h1>
      
      <% @users.each do |user| %>
        <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">
          <%= image_tag user.avatar, class: "img-responsive" %>
          
          <h4><%= link_to user.email.split('@').first, user_path(user) %></h4>

          <!--使用新增追蹤按鈕的prtial-->  
          <%= render partial: "shared/follow", locals:{user:user} %>

          <!--使用新增好友按鈕的prtial-->  
          <%= render partial: "shared/friend", locals:{user:user} %>

        </div>
      <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <!-- page-header 裡面顯示個人檔案資料 -->
      <div class="page-header">  
        <div class="col-md-3 col-sm-4">
          <div class="text-center">
          <%= image_tag @user.avatar, class:"img-responsive img-rounded" %>
          </div>
        </div>

        <div class="col-md-9 col-sm-8">
          <h2><%= @user.name %></h2>
          <p><strong><%= @user.email %></strong></p>
          <div><%= simple_format @user.intro %><div>
          <% if @user.email == current_user.email %>
            <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary" %>
          <% end %>
          <%= link_to 'myfriend' , friend_list_user_path(@user), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="clearfix"></div>

  <br>


      
    <div class="col-md-4">

      <!-- 顯示自己去追蹤的人的清單 -->
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><strong><%= @user.followings.count %></strong> followings</h3>
        </div>
        
        <ul class="list-group">
          <% @followings.each do |following| %>
          <li class="list-group-item">
            <%= link_to user_path(following) do %>
            <%= image_tag following.avatar, height: 30, width: 30, class: "img-circle" %>
            
            <% if following.name? %>
            <%= following.name %>
            <% else %>
            <%= following.email.split('@').first %>
            <% end %>
            
            <% end %>
          </li>
          <% end %>
        </ul>
        
      </div>

      <!-- 顯示追蹤自己的人的清單 -->
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><strong><%= @user.followers.count %></strong> followers</h3>
        </div>
        
        <ul class="list-group">
          <% @followers.each do |follower| %>
          <li class="list-group-item">
            <%= link_to user_path(follower) do %>
            <%= image_tag follower.avatar, height: 30, width: 30, class: "img-circle" %>
            
            <% if follower.name? %>
            <%= follower.name %>
            <% else %>
            <%= follower.email.split('@').first %>
            <% end %>
            
            <% end %>
          </li>
          <% end %>
        </ul>
        
      </div>

    </div>

    <div class="col-md-8 col-sm-8">

      <!-- 顯示已評論餐廳的清單，panel包一個panel-body裡面使用row>col的layouts來顯示評論 -->
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</h3>
        </div>
        <div class="panel-body">
          <% @commented_restaurants.each do |restaurant| %>
            <%= link_to restaurant_path(restaurant) do %>
            <div class="my-restaurant">
              <div>
                <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
              </div>
              <h5><%= restaurant.name %></h5>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>

      <!-- 顯示已收藏餐廳的清單 -->
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><strong><%= @favorited_restaurants.count %></strong> 已收藏餐廳</h3>
        </div>
        <div class="panel-body">
          <% @favorited_restaurants.each do |restaurant| %>
            <%= link_to restaurant_path(restaurant) do %>
            <div class="my-restaurant">
              <div>
                <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
              </div>
              <h5><%= restaurant.name %></h5>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <div>
</div>